import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import './globals.css'
import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import ThemeProviderWrapper from "@/providers/ThemeProviderWrapper/ThemeProviderWrapper";
import StoreProvider from "@/providers/ThemeProviderWrapper/storeProvider";

const InriaSans = Inria_Sans({
  weight: ['400', '700'], 
  variable: "--font-inria-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${InriaSans.variable}`}>
       <StoreProvider>
        <ThemeProviderWrapper>{children}
        </ThemeProviderWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}

